name: naivedhya_delivery_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  app_settings: ^6.1.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_gen: ^5.11.0
  flutter_local_notifications: ^19.4.0
  flutter_localizations:
    sdk: flutter
  geolocator: ^14.0.2
  get_it: ^8.2.0
  google_maps_flutter: ^2.12.3
  http: ^1.5.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.9.1
  url_launcher: ^6.3.2
  intl: any

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  
  # Add your assets here if needed
  # assets:
  #   - images/
  
# Localization configuration
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations